### ISSUE TITLE
System extensions page - consistency

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/DocsTypo3Org-Homepage#177]
todos:

* [x] use card layout
* [x] remove comments
* [x] add description
* [x] add package name

----

Systems extension page: https://docs.typo3.org/Home/SystemExtensions.html

Here #176 @mbrodala made a good point - should we have a comment when extension was added, e.g. for rte_ckeditor:

> Documentation added in 2/2019, rte_ckeditor available since TYPO3 8.7 LTS

I think it is not necessary, but we can also think about the structure in general, e.g. 

* should comments column be removed?
* should comments be changed to **description** and contain (short!) description, as already done for fluid_styled_content

> Comment: Content Elements based on Fluid

*  .... formatted differently entirely?

For beginners, I think it may be helpful to have a description.

**Comment by mbrodala** [comment]
IMO we can drop the *Comment* column from the table of current extensions altogether. This also puts more emphasis on this column for the obsolete extensions below.

A *Description* column as replacement would be useful but must be kept updated.

**Comment by alexander-nitsche** [comment]
I suggest to extend this page and list all system extensions here, with optional links to Packagist, TER and Docs and a description, which contains common description without many details so that it has not to be updated often. If all system extensions are listed here, the page helps to decide if a new extension has to be developed or not besides providing the links to the docs. Each extension item should contain the TYPO3 extension key as well as the Composer package name, so that the list can be used in many contexts. Maybe the table structure has to be replaced by a list structure or similar to provide more space per entry.

Having a look at the page context we are in the middle of explaining the extension development and the area starts with https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/Introduction/Index.html where all sources of extensions are explained, but not all are linked: i would add there in the first paragraph the missing link to this system extensions page, and in the fifth paragraph the link to the extension development page. I would move the types of extensions there into an own section with own headline below the section "Extensions and the Core", for example "Types of Extensions". I would remove the system extensions listed in section "Notable system extensions" and merge useful information into the system extensions page of this issue.

**Comment by sypets** [comment]
ok, Susi also suggested to use the card layout for the page. I think your suggestions are good and probably best to create a draft and see how it looks.

btw. I also suggested to list the system extensions on extensions.typo3.org. That might also be something to think about, then we don't need this page for system extensions on docs at all - we just link to extensions.typo3.org where all the links (to docs, to crowdin, to the source code etc.) are already created automagically. 

I would prefer that (but don't know if it will be implemented) - https://git.typo3.org/services/t3o-sites/extensions.typo3.org/ter/-/issues/385

We already are editing information in various places - would be cool if possible to reduce that.
