### ISSUE TITLE
Add ViewHelper namespace & examples to auto-generated references

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/DocsTypo3Org-Homepage#48]
* e.g. https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/backend/9.5/Index.html
* e.g. https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/backend/9.5/Avatar.html

Possible Changes

* add information on Fluid ViewHelper namespace and what needs to be integrated `{namespace be=}` or `xmlns:be=http://typo3.org/ns/...`
* add examples on how to use it (probably needs to be defined in ViewHelper implementation first)

**Comment by susannemoog** [comment]
The whole viewhelper documentation is "difficult" for us to handle because it is auto-generated directly from the core code by using https://github.com/TYPO3-Documentation/fluid-documentation-generator - I don't think we can auto-generate the info from the documentation side, because we don't know how / which namespace the implementation uses. I think this needs to be fixed / added to the core viewhelper implementations. Can you please open an issue in forge if you agree or comment here if you disagree and have an idea on how to fix this on this side?
