### ISSUE TITLE
Provide basic help about using the website

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/DocsTypo3Org-Homepage#5]
At SwaggerHub I found
![091](https://cloud.githubusercontent.com/assets/307057/22036094/9680f9be-dcf2-11e6-8141-efed0d6b862e.png)

Or use an help overlay:

![092](https://cloud.githubusercontent.com/assets/307057/22036601/5b2bd634-dcf4-11e6-8f98-5401b72a28f9.png)

**Comment by sypets** [comment]
@marble Do you mean help on using docs.typo3.org or using TYPO3 in general?

**Comment by sypets** [comment]
Also see TYPO3Worx, which already has an excellent description: https://typo3worx.eu/2017/01/guide-to-typo3-documentation-part-1-the-ui/

How about, we add a menu entry, e.g. "How to use TYPO3 documentation" with at least the most important information:

* how to use search
* how to use version switcher

and the additional link to https://typo3worx.eu/2017/01/guide-to-typo3-documentation-part-1-the-ui/

**Comment by sypets** [comment]
I added "Usage Tips": https://docs.typo3.org/Tips/UsingThisSite/Index.html

Some of these tips are linked from the start page. 

Instead of "Usage Tips", I think it would be better to work on usability in general, to make some of the usage tips not necessary and usage more intuitive (_if_ that is possible). But, that must be addressed in theme repository: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd

**Comment by susannemoog** [comment]
I think Sybilles tips already help a lot. Thanks to the sidebar possibilities of the theme, we now have them linked prominently on the home page. I will close this issue for now. We can revisit that topic anytime :)
